site_name: Compose Data Viz Docs
theme:
  name: material

# Tell MkDocs to look one folder up (the root of the 'docs' folder) for .md files
docs_dir: '../'

# Tell MkDocs to output the built site to the root of your project
# (so you don't end up with docs/site-deps/site/)
site_dir: '../../site'